blueprint:
  name: Forward persistent notification to mobile device
  description: An automation that forwards notifications to mobile device as push messages.
    Also makes sure to remove the notification from devices if dismissed from other device or web.
  domain: automation
  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications.
      selector:
        device:
          filter:
          - integration: mobile_app
          multiple: false

mode: queued
max: 100

trigger:
  - platform: persistent_notification
    update_type:
      - added
      - removed
    notification_id: ""
action:
  - choose:
    - conditions:
        - alias: Notification added
          condition: template
          value_template: "{{ trigger.update_type == 'added' }}"
      sequence:
        - alias: Send notification
          domain: mobile_app
          type: notify
          device_id: !input notify_device
          title: "{{ trigger.notification.title }}"
          message: "{{ trigger.notification.message }}"
          data:
            sticky: true
            tag: "{{ trigger.notification.notification_id }}"
    - conditions:
        - alias: Notification removed
          condition: template
          value_template: "{{ trigger.update_type == 'removed' }}"
      sequence:
        - alias: Clear notification
          domain: mobile_app
          type: notify
          device_id: !input notify_device
          message: clear_notification
          data:
            tag: "{{ trigger.notification.notification_id }}"
